### ISSUE TITLE
Boolean productions too general?

### ISSUE THREAD

**Issue by rewinfrey** [tree-sitter/tree-sitter-javascript#11]
While adding more specific syntax types for Diff Summaries, @joshvera and I noticed that the `Booleans` productions supported by TreeSitter of `true`, `false`, `this`, `undefined` and `null` [defined here](https://github.com/tree-sitter/tree-sitter-javascript/blob/ce3636a0e1dbe610e01c7ddd876f476e37666769/grammar_test/expressions.txt#L63-L79) include terms that are not defined in the [ECMA 6 specification's definition of boolean literals](http://www.ecma-international.org/ecma-262/6.0/#sec-terms-and-definitions-boolean-type).

I don't have any of the historical context or the decisions made that grouped these terms as Boolean productions, but it makes us wonder if we should consider producing `BooleanLiteral` productions for `true` and `false`?

This would mean that the following:

```javascript
true;
false;
```

Would produce:

```javascript
(program
  (expression_statement (boolean_literal))
  (expression_statement (boolean_literal)))
```

This would also mean treating `this`, `undefined` and `null` as separate productions.

As a possible idea, the following:

```javascript
this;
null;
undefined;
```

Could produce:

```javascript
(program
  (expression_statement (this_expression)
  (expression_statement (null_literal)
  (expression_statement (undefined_type))
```

The above possible productions are based on the ECMA 6 spec's [`NullLiteral`](http://www.ecma-international.org/ecma-262/6.0/#sec-null-literals) and [`undefined type`](http://www.ecma-international.org/ecma-262/6.0/#sec-terms-and-definitions-undefined-type). There is not an associated `UndefinedLiteral`.

However, the `null` and `undefined` productions suggested here may be overblown or unnecessary. The question this issue is most concerned with is would it make sense to represent `true` and `false` terms as `boolean_literal` productions?

**Comment by maxbrunsfeld** [comment]
To summarize conversation w/ @joshvera and @rewinfrey -

The grammar already differentiates between `this`, `null`, `undefined`, `true` and `false`. The names are slightly different than the ones suggested above though (`null` vs `null_literal`, `undefined` instead of `undefined_type`). I'm not super strongly tied to the current names, but as of now, I like the shorter ones that resemble the way people talk about code casually.

I'm also open to grouping `true` and `false` together. My thought right now is that we don't lose anything by keeping them separate, and it may sometimes be useful to be able to distinguish `true` from `false` in the syntax tree (like searching for `while (true)` or `return false` or something).

The description in the test that you referenced ('Boolean expressions') is definitely somewhat inaccurate. @rewinfrey are you interested in rewording that thing, or possibly splitting it into multiple tests to correct the grouping? Aside from that, are you ok w/ closing this out?

**Comment by rewinfrey** [comment]
Thank you for summarizing @maxbrunsfeld! :bow:

> I'm not super strongly tied to the current names, but as of now, I like the shorter ones that resemble the way people talk about code casually.

This sounds good to me 👍 

> possibly splitting it into multiple tests to correct the grouping?

I wonder if there is a more general name we could give the grouping? Is there a general name for 'standalone' identifier?

I'm good with closing this out! Thank you for clarifying for us. Also early welcome back from parental leave. 😄 

Also to note, in the future if we do decide to add a `boolean_literal` production it would not be a costly change on the Diff Summaries side of things.
