### ISSUE TITLE
Incorrect parse error on array destructuring when LHS includes a property access

### ISSUE THREAD

**Issue by eaftan** [tree-sitter/tree-sitter-javascript#178]
The following code

```
[obj.a] = [a];
```

is parsed by tree-sitter as 

```
program [0, 0] - [1, 0]
  expression_statement [0, 0] - [0, 14]
    subscript_expression [0, 0] - [0, 13]
      object: array [0, 0] - [0, 7]
        member_expression [0, 1] - [0, 6]
          object: identifier [0, 1] - [0, 4]
          property: property_identifier [0, 5] - [0, 6]
      ERROR [0, 8] - [0, 9]
      index: identifier [0, 11] - [0, 12]
```

If I remove the `.a` from the LHS, it parses without error.

**Comment by lalitmee** [comment]
I am also facing a similar issue which is related to destructuring of objects. Here are some screenshots.

1. Syntax highlighting is disturbed and after a point in the file, all the code is looking like a string because it is getting the syntax highlighting of a string.

![image](https://user-images.githubusercontent.com/10762218/122699925-f6dbda80-d267-11eb-8993-bf781cda32dc.png)

2. Syntax highlighting is disturbed and after the first property, other properties are not syntax-highlighted correctly.

![image](https://user-images.githubusercontent.com/10762218/122699996-16730300-d268-11eb-8fa0-2dcb90a3a91c.png)

3. Broken syntax highlighting with the `treesitter-playground`.

![image](https://user-images.githubusercontent.com/10762218/122700012-1e32a780-d268-11eb-941b-c1fbd9c1e528.png)

**Comment by mjambon** [comment]
Could you please post a link to the [typescript playground](https://www.typescriptlang.org/play) with a minimal program that works? I just don't know this typescript/javascript feature and it would save me some time. Thank you!

**Comment by mjambon** [comment]
ok, I see. I didn't understand how javascript patterns worked.
[typescript playground](https://www.typescriptlang.org/play?#code/MYewdgzgLgBCBGArGBeGBvAhgLgAwBoZ5sBGAXwG4AoAbQUQDpND6H4BdVGOpNl3zO2qhIIADYBTBmJABzABT0AlNSA)
Minimal example:
```
$ tree-sitter parse <(echo '[a.b] = c')
(program [0, 0] - [1, 0]
  (ERROR [0, 0] - [0, 7]
    (array [0, 0] - [0, 5]
      (member_expression [0, 1] - [0, 4]
        object: (identifier [0, 1] - [0, 2])
        property: (property_identifier [0, 3] - [0, 4]))))
  (expression_statement [0, 8] - [0, 9]
    (identifier [0, 8] - [0, 9])))
/dev/fd/63	0 ms	(ERROR [0, 0] - [0, 7])
```
