### ISSUE TITLE
Split JSX into separate grammar?

### ISSUE THREAD

**Issue by HiPhish** [tree-sitter/tree-sitter-javascript#244]
As a user I want to be able to have separate settings for Javascript and JSX in my configuration. Currently support for JSX files (React.js extension for Javascript) is included in the Javascript grammar. However, Javascript and JSX are different languages, and I want to have separate per-filetype settings in my text editor.

I have recently added support for JSX in [nvim-ts-rainbow2](https://gitlab.com/HiPhish/nvim-ts-rainbow2) where I have two sets of queries for JSX files: one matches the angle brackets of tags, other other matches entire tags. This means a lot of copy-pasting between both queries.

If the two file types were separate I could make the JSX query inherit the Javascript query and add only the queries for the JSX extension. Example in TSX, note the first line which Neovim understands:

```; inherits: typescript

(jsx_element
  open_tag: (jsx_opening_element) @opening
  close_tag: (jsx_closing_element) @closing) @container
```

This is only possible because the https://github.com/tree-sitter/
[tree-sitter-typescript](https://github.com/tree-sitter/tree-sitter-typescript) repo splits the two languages this way as well. The result is a very terse query. If I want to change how I highlight tags I only need to write a query for that part and can piggy-back off the Typescript query for everything else.

**Comment by amaanq** [comment]
PR Welcome - though I do find having it as one language simpler, but I can see the benefits of splitting it.

**Comment by calebdw** [comment]
PR submitted :)

**Comment by maxbrunsfeld** [comment]
Hi, I don't think we want a separate grammar for JSX, because in most codebases, you can't tell whether a file is going to use JSX statically. They often just use the `.js` extension.

**Comment by calebdw** [comment]
@maxbrunsfeld 

How is splitting javascript/jsx any different than splitting typescript/tsx? Since the ts parser is split it makes sense to split this one, otherwise the same argument for keeping this parser combined could apply to the ts parser, could it not?


> They often just use the .js extension.

That may be, however, I would argue that jsx is not javascript and therefore should not be included in `.js` files. Perhaps splitting the parser would provide the motivation to separate those concerns?

**Comment by HiPhish** [comment]
> They often just use the `.js` extension.

Do they really? I have only worked with React and Typescript, and the file extension was always `.tsx`. Wouldn't React and Javascript projects use `.jsx`?

**Comment by maxbrunsfeld** [comment]
> How is splitting javascript/jsx any different than splitting typescript/tsx? Since the ts parser is split it makes sense to split this one, otherwise the same argument for keeping this parser combined could apply to the ts parser, could it not?

TypeScript and TSX *must* use different file extensions, because the two languages are mutually incompatible. So the TypeScript compiler needs to know up front which is which.

In practice, JavaScript is not that way. People just use the `.js` extension for files that contain JSX. As the maintainers of this repo, we don't have any control over this. With the current system, the JavaScript grammar can be applied to JS files. If we were to split the grammars, it would never be clear when we should use the plain JS grammar. So that would be a strictly less useful state of affairs for consumers of this library.

**Comment by calebdw** [comment]
Should this issue be closed then?

**Comment by NullVoxPopuli** [comment]
> They often just use the .js extension.

In every JSX-using codebase I've seen in the last 7 years, folks have been pretty good about using JSX for jsx and JS for non-JSX
